name: mom6_solutions
channels:
    - conda-forge
    - nodefaults
dependencies:
    - numpy
    - xarray
    - matplotlib
    - cartopy
    - dask
    - jupyter
    - jupyterlab
    - netCDF4
    - ncar-jobqueue
    - nc-time-axis
    - dask-labextension
    - pip:
      - git+https://github.com/NCAR/mom6-tools.git
